"""create patients and diagnoses

Revision ID: 30496e383b13
Revises: 
Create Date: 2026-06-14 10:03:33.061417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30496e383b13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint('age >= 0 AND age <= 150', name='ck_patients_age_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index('idx_patients_deleted', ['is_deleted'], unique=False)
        batch_op.create_index('idx_patients_name', ['name'], unique=False)
        batch_op.create_index('idx_patients_patient_id', ['patient_id'], unique=False)

    op.create_table('diagnoses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('contour_path', sa.String(length=500), nullable=True),
    sa.Column('lesion_areas', sa.Text(), server_default='{}', nullable=False),
    sa.Column('lesion_counts', sa.Text(), server_default='{}', nullable=False),
    sa.Column('severity', sa.String(length=50), server_default='正常', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.create_index('idx_diagnoses_created', ['created_at'], unique=False)
        batch_op.create_index('idx_diagnoses_deleted', ['is_deleted'], unique=False)
        batch_op.create_index('idx_diagnoses_patient', ['patient_id'], unique=False)
        batch_op.create_index('idx_diagnoses_patient_active', ['patient_id', 'is_deleted'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.drop_index('idx_diagnoses_patient_active')
        batch_op.drop_index('idx_diagnoses_patient')
        batch_op.drop_index('idx_diagnoses_deleted')
        batch_op.drop_index('idx_diagnoses_created')

    op.drop_table('diagnoses')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index('idx_patients_patient_id')
        batch_op.drop_index('idx_patients_name')
        batch_op.drop_index('idx_patients_deleted')

    op.drop_table('patients')
    # ### end Alembic commands ###
